certificate.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls
  namespace: default
spec:
  secretName: myapp-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  issuerRef:
    name: myapp-issuer
    kind: Issuer
