ingress-nginx namespace'inde oluşturulması gereken secret dosyası



apiVersion: v1
data:
  tls.crt: base64enc.crt
  tls.key: bse64enc.key
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: myapp
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-06-11T09:05:16Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: myapp-tls
  namespace: ingress-nginx
  resourceVersion: "178948"
  uid: 20db229a-9f0b-44f2-b7e2-c1ebea07f3ca
type: kubernetes.io/tls
