secret.yaml

#Helm bu projede, uygulamanın Kubernetes cluster'ında kolayca yönetilmesini sağlamak için kullanıldı. Uygulamanın kurulumu, yapılandırması ve güncellenmesi Helm chart'ları aracılığıyla gerçekleştirildi.
#Ayrıca, TLS sertifikalarının yönetimi de Helm chart'ları kullanılarak otomatikleştirildi. Bu sayede, uygulamanın Kubernetes ortamında yönetimi basitleştirildi ve standart hale getirildi.

apiVersion: v1
kind: Secret
metadata:
  name: myapp-tls
  namespace: default
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
type: kubernetes.io/tls
